"""Remove tenant_id from Ticket model

Revision ID: b2e139ac239c
Revises: 7993dca8852e
Create Date: 2025-03-18 11:52:56.014442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e139ac239c'
down_revision: Union[str, None] = '7993dca8852e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('tickets', sa.Column('priority_id', sa.Integer(), nullable=False))
    op.drop_constraint('tickets_tenant_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'priorities', ['priority_id'], ['priority_id'])
    op.create_foreign_key(None, 'tickets', 'status', ['status_id'], ['status_id'])
    op.drop_column('tickets', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_tenant_id_fkey', 'tickets', 'tenants', ['tenant_id'], ['tenant_id'])
    op.drop_column('tickets', 'priority_id')
    op.drop_column('tickets', 'status_id')
    # ### end Alembic commands ###
